### ISSUE TITLE
 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by Yukun4119** [double-point/craw_project#1]
报错如下：
File "main_ncp.py", line 47, in <module>
    df_city_data, df_province_data = craw_info(browser, url)
  File "/Users/syk/Desktop/craw_project-master/craw_NCP/craw_NCP_info.py", line 49, in craw_info
    soup_city_class = soup.find('div', class_='areaBox___Sl7gp themeA___1BO7o numFormat___nZ7U7 flexLayout___1pYge').\
AttributeError: 'NoneType' object has no attribute 'find_all'

是不是因为网站的class已经修改了，但是更新class之后还是没搞定

**Comment by double-point** [comment]
先检查一下你是否真正爬到了整个网页的源码吧，然后在检查爬下的源码里面数据位置
（另：我这边地市数据爬取正常，但是官网页面比一个月前改动较大，只能拿到部分数据，主要是动态加载）

**Comment by double-point** [comment]
ok
